# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f545e94c72545a77b64af42a1e19aa9103ab1f9372101f81ccedc23fccd2dd90eef722c80ac1b42224ee3442bf505fad95d8945720d05163c03c81caf4b5d2bf

test:
  secret_key_base: 6ed6eb589852354754975c240f35d768926228624ef2f089ac9ddab3c054f12c8067ed9f63f8026baf698c2b17f19b0574ddcfca043739d6995341356949d57d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
